import Head from 'next/head'
import Header from '@/components/Header'
import Search from '@/components/Search'
import CountryFilter from '@/components/CountryFilter'
import Card from '@/components/Card'

export default function Home({ countryList }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className='flex flex-col md:flex-row justify-between px-4 py-6 md:p-16 space-y-8 md:space-y-0'>
          <Search />
          <CountryFilter />
        </div>
        <div className='p-8 md:p-16 grid sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-6'>
          {
            countryList?.map((country) => <Card name={country.name?.official || country.name.common} population={country.population} region={country.region} flag={country.flags.png} capital={country.capital || '-'} />)
          }
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const countryList = await fetch('https://restcountries.com/v3.1/all').then((res) => res.json())
  return {
    props: {
      countryList
    }
  }
}
